opentdf/tests

abacus-integration-test/e2e/Attributes.spec.ts
abacus-integration-test/e2e/Authorities.spec.ts
abacus-integration-test/e2e/helpers/operations.ts
abacus-integration-test/playwright.config.ts

2. Split large test to smaller
3. Replaced old $$ to locators
4. Fixed failed clean up for 'delete autority test'
5. Added describe steps for better consistency in reports/debug
6. Fixed 404 error
7. Added wait seletors for some tests

E2e test improvements

---

xtest/abac.py
xtest/conftest.py
xtest/tdfs.py
xtest/test_abac.py
xtest/test_tdfs.py

- Validates that manifests are well formed using pydantic written from the spec
- In abac tests, validates that the KAOs have the format expected for shares and splits

chore(xtest): Adds ztdf manifest assertions

---

xtest/test_abac.py

chore(xtest): Canonical kas path is /kas

---

xtest/abac.py
xtest/test_abac.py

- Cleans up types for kas registry around new 'cached' key type
- This isn't yet added to the test since java is failing to deserialize the type properly

chore(xtest): Clean up cached kas key support

---

xtest/conftest.py
xtest/test_abac.py

- Move attribute and grant creation to fixtures, and updates the abac tests to use them
- This simplifies the test bodies, as they now can focus on encrypt and decrypt
- skips js on encrypt tests for now, as they don't yet support abac configuration
- This means that running locally you can now use the `pytest --sdks go` argument, for example, to test just  the go SDK, and `pytest --encrypt-sdks java test_abac.py` to test all the SDKs for decrypt but just the java SDK for encrypt with abac-based configuration

refactor(xtest): let abac tests use fixtures

---

.github/workflows/xtest.yml
xtest/test_abac.py

Related to https://github.com/opentdf/platform/issues/1530

feat(ci): update x-test to use reusable platform start and kas spin up composite actions

---

xtest/sdk/js/cli/cli.sh
xtest/tdfs.py
xtest/test_abac.py

- Adds new `supports(sdk, *feat)` function to 'tdfs' to simplify feature testing during tests
- Updates ns grant and autoconfigure abac tests to use new function
- Updates logic for js sdk autoconf testing to run `opentdf.mjs help` and check for presence of 'autoconfigure' option

chore(xtest): Allow autoconfigure to work in js

---

xtest/sdk/js/cli/cli.sh
xtest/tdfs.py

I'm adding support for ns grants at the same time as autoconfigure

chore(xtest): autoconf js clients use ns grants

---

xtest/conftest.py
xtest/sdk/go/cli.sh
xtest/sdk/java/cli.sh
xtest/sdk/js/cli/cli.sh
xtest/tdfs.py
xtest/test_tdfs.py

Adds a new container type, nano-with-ecdsa, that is currently skipped for all except go sdk

chore(xtest): Adds checks for ecdsa

---

.github/workflows/xtest.yml
xtest/test_tdfs.py

Check the error output for tamper errors to ensure they are categorized as tamper

feat: Check err output for tamper errors

---

.github/workflows/check.yml
.github/workflows/xtest.yml
xtest/assertions.py
xtest/conftest.py
xtest/sdk/go/cli.sh
xtest/sdk/java/cli.sh
xtest/sdk/js/cli/cli.sh
xtest/tdfs.py
xtest/test_tdfs.py

Adding tests for creating tdfs with assertions with provided keys, and decrypting those tdf and verifying those assertions with the provided assertion verification keys
tests both hs256 and rs256

feat: Assertion verification tests with signing keys

---

xtest/sdk/java/cli.sh
xtest/sdk/js/cli/cli.sh
xtest/tdfs.py
xtest/test_abac.py
xtest/test_tdfs.py

- If encrypt produces a 'hexless' TDF, don't bother testing with older SDK on decrypt
- Currenly, only supports JS library

chore(xtest): Allow 'hexless' upgrade

---

xtest/abac.py
xtest/assertions.py
xtest/conftest.py
xtest/nano.py
xtest/test_abac.py
xtest/test_legacy.py
xtest/test_tdfs.py

I turned my vscode pylance >  Python: Analysis: Type Checking Mode to 'strict' and fixed some/most of the issues it found. This should reduce some of the noise in the pytest logs

chore(xtest): pyright suggestions

---

xtest/conftest.py
xtest/sdk/js/cli/cli.sh
xtest/tdfs.py
xtest/test_tdfs.py

- the JS help string is breaking on the detected keyword, so I picked one that is less likely to suffer word wrap issues
- While I'm here, renames 'format_type' to 'container_type' to match the custom arg name
- Improve debug logging of script invoker to include environment variables, as that is the way we are adding more features now instead of using positional parameters
- Fix bug where ecwrap wasn't being done on encrypt (it was being used for the return rewrap though)

chore(xtest): Fixes ecwrap detection on js

---

xtest/sdk/java/cli.sh
xtest/test_tdfs.py

Previously, encrypt with the same sdk/container types were shared in the 'created files' cache, even in the containers had different configuration options. This update should correctly generate new versions of the files when presented with new options. Currently, this means some tests were passing might have failed for nano (ECDSA v. GMAC policy bindings) and ZTDF (ec-wrapped v. RSA wrapped KAOs)

chore(xtest): Fix error in dedupe-encrypt logic

---

.github/workflows/xtest.yml
xtest/README.md
xtest/conftest.py
xtest/tdfs.py
xtest/test_abac.py
xtest/test_legacy.py
xtest/test_tdfs.py

Focusing on a specific SDK, `go`, `java`, or `js`, will only execute tests that involve that SDK, skipping all tests that are from or between other SDKs, e.g. if `focus == 'go'`, tests won't run that compare outputs between `js` and `java`, that don't involve the go sdk.

feat(xtest): Adds xtest `focus-sdk` parameter

---

.github/workflows/xtest.yml
xtest/sdk/scripts/resolve-version.py
xtest/setup-cli-tool/action.yaml

Ths lets the `resolve-versions` script handle `refs/pulls/[number]/{merge,head}` style ref names.
It also fixes a remaining `checkout` action that was missing the `repository` parameter

chore(xtest): Fix for pull requests

---

xtest/sdk/go/cli.sh
xtest/sdk/java/cli.sh
xtest/sdk/js/cli.sh
xtest/tdfs.py

We briefly enabled ec-wrap key access objects in most clients with a different salt value for the hkdf during development. This should skip testing the ecwrap feature on those clients now that we've enabled skew testing

chore(xtest): Skips nonconformant ecwrap clients

---

xtest/sdk/java/cli.sh
xtest/tdfs.py
xtest/test_abac.py
xtest/test_legacy.py
xtest/test_tdfs.py

This feature is broken in 0.7.6, and unlike web-sdk, since the KAOs are parsed before being passed to rewrap, new fields are dropped

chore(xtest): Skip ecdsa tests on older java-sdks

---

.github/workflows/xtest.yml

- Don't link in older, incompatible versions of platform

chore(xtest): Fix for skew testing go

---

.github/workflows/xtest.yml
xtest/sdk/go/cli.sh
xtest/sdk/scripts/resolve-version.py
xtest/setup-cli-tool/action.yaml

Required changes to let the otdfctl repo dispatch skew tests
- Adds a 'head' flag for checked out source SDKs
- For otdfctl, use this to indicate we should be using the checked-out version of plat for the libraries in that repo. For example, this now properly sets up a go workspace for pull requests on the otdfctl repo
- While here, also stops doing testing assertions with older versions of otdfctl (before we added verification) because their format is unreliable (unsurprising as we had no CI in place to test it)
- Lets merge request descriptions be prettier in the summary
- Stop dynamically loading the manifest. This was causing test failures due to this job getting 429'd

chore(xtest): Lets go work otdf ctl 🤝 plat

---

xtest/sdk/java/cli.sh
xtest/sdk/js/cli.sh
xtest/tdfs.py
xtest/test_abac.py
xtest/test_tdfs.py

- If the sdk tool supports 'target mode', downtarget older SDKs during skew testing
- Adds a 4.2.2 test that runs iff the encrypt SDK under test supports downtargeting

chore(xtest): Support 'target mode' option

---

xtest/tdfs.py

- only ztdf containers support mode targeting at the moment
- removes a hallucination I missed when I asked claude to memoize supports

chore(xtest): Fix java-sdk nano tests

---

xtest/conftest.py
xtest/tdfs.py
xtest/test_abac.py
xtest/test_legacy.py
xtest/test_nano.py
xtest/test_tdfs.py

Some advantages to the `pathlib` object:
- Lets us use `/` to join paths instead of more verbose `os.path.join`
- Less likely to accidentally have invalid chars in path
- Better suggestions when combined with strict types (via pyright or similar)
While here, also stops unzipping the whole package when just validating manifest schemas.
This also cleans up some of the file names in the tmp folder, making local debugging easier as the file names more clearly match the sdk version and scenario

chore(xtest): Prefer Paths to str for files & dirs

---

.github/workflows/xtest.yml
xtest/sdk/.gitignore
xtest/sdk/java/Makefile
xtest/sdk/scripts/post-checkout-java.sh
xtest/sdk/scripts/resolve-version.py
xtest/setup-cli-tool/action.yaml

This uses the platform.branch build property in the java-sdk build system to build appropriate protocol buffers as needed.
1. For skew tests with older builds, where the property wasn't defined, retro-actively add it and pin to an appropriate tag. (Right now, this is the tag that was last added when the java tag was released, but I suspect we will need something more nuanced)
2. For tests from java-sdk pull requests, use the main version of plat when testing against platform head; for tests with released platforms, use the baked version
3. For tests from platform pull requests, let the head version of the java sdk use the platform head; for tests with released java-sdk, use the baked in version
This invoves:
- extending resolve-version.py with a lookup table matchching old releases of …

chore(xtest): Let main java-sdk target plat main

---

.github/workflows/xtest.yml

the github script references env vars that dont exist, add them

fix(xtest): add refs to env in resolve-versions

---

.github/workflows/xtest.yml
xtest/sdk/go/cli.sh
xtest/sdk/java/cli.sh
xtest/sdk/js/cli.sh
xtest/test_tdfs.py

add a test for the case where someone edits a kao in the manifest with a malicious url. with the kas-allowlist feature, the sdk should throw an error for this url as it is not in the kas registry

feat(xtest): Test for malicious kao

---

.github/workflows/xtest.yml
xtest/sdk/js/cli.sh
xtest/test_tdfs.py

fix js sdk checkout
enable kao tamper tests, adjust errors to include js thrown error

feat(xtest): Enable kao tamper tests for js sdk

---

.github/workflows/xtest.yml
xtest/sdk/scripts/resolve-version.py

- look up branch names (refs/heads)
- don't try to use versions that resolve to `err`

chore(ci): Fix xtest on sdk branches

---

.github/workflows/xtest.yml

The idea is:
- weekly: test all current supported releases
- semi-weekly: tests main against LTS
- daily: test all releases against current release

chore(xtest): Fix scheduled run versions

---

.github/workflows/check.yml
.github/workflows/vulnerability.yml
.github/workflows/xtest.yml
xtest/assertions.py
xtest/conftest.py
xtest/requirements.txt
xtest/sdk/scripts/resolve-version.py
xtest/setup-cli-tool/action.yaml
xtest/tdfs.py

- Adds `pyright` to the linter list (along with `black` and `ruff`)
- pyright it used by pylance under the hood, so this should ensure fewer squigglies in vscode with that python language server enabled
- `schema` is reserved in the pydantic BaseModel; this makes the output cleaner by removing a warning about this
- Fixes a couple of issues that pyright had a problem with not inferring type guards as in the spec AFAICT
- Also removes the 'type' parameter from composite actions, which is not present
This doesn't currently block on pyright errors. They are instead pasted into the summary page for lints.
Warnings and informations continue to be hidden in the logs
Error sample [run](https://github.com/opentdf/tests/actions/runs/15326517394):
Warning sample …

chore(xtest): Adds pyright to CI

---

.github/workflows/xtest.yml
xtest/conftest.py
xtest/test_nano.py
xtest/test_tdfs.py

This reverts commit cb3576ea8bfc5bdb9d431f104793384a3f5d8e0a.

chore(xtest): Revert Prefer pathless kas uris (#320)

---

.github/workflows/xtest.yml
xtest/tdfs.py

when modifying tdfs to test error conditions we'd read a field named `.schema` and writing one named `.schema_`.
[we had the alias in place](https://github.com/opentdf/tests/blob/324ac800166adc98641640556bd2d9776df61972/xtest/assertions.py#L15) but it was ignored during serialization without `by_alias=True`
[it looks like running the java sdk (at least)](https://github.com/opentdf/tests/actions/runs/16472645962/job/46565640776) from a branch is broken so I want to merge this under the theory
that it doesn't make anything worse.
```
Error:  The goal you specified requires a project to execute but there is no POM in this directory (/home/runner/work/tests/tests/otdftests/xtest/sdk/java/src/dspx-817). Please verify you invoked Maven from the correct directory. -> [Help 1]
```

fix: we were serializing `assertion.statement.schema` as `schema_`

---

xtest/tdfs.py
xtest/test_policytypes.py

Adds xtest assertions that policies contain the requested attributes. NOTE this currently only works for plain text policies, not encrypted policies

chore(xtest): Add assertions about policy contents

---

.github/workflows/check.yml
.github/workflows/xtest.yml

Small feedback PR, relating to https://github.com/opentdf/tests/pull/331

feat: Do less work
