opentdf/tests

- .github/workflows/tdf3-test.yml
- .github/workflows/vulnerability.yml
- .github/workflows/xtest.yml
- Have our GitHub workflows run on schedules
- Regular tests run twice a day
- Vulnerabilities run three times a week
> 📆 cronify our GitHub workflows

- .github/workflows/client-web-test.yml
- .github/workflows/vulnerability.yml
- .github/workflows/xtest.yml
> Trigger Playwright tests run in post-commit test in opentdf/tests

- .github/workflows/abacus-playwright-tests.yml
- .github/workflows/vulnerability.yml
It was instead looking for the latest abacus image tag, not the chart tag
> 🐛 Fix skopeo lookup for abacus chart

- .github/workflows/abacus-playwright-tests.yml
- abacus-integration-test/e2e/App.spec.ts
- abacus-integration-test/e2e/Attributes.spec.ts
- abacus-integration-test/e2e/helpers/operations.ts
- abacus-integration-test/e2e/helpers/selectors.ts
> Integrate latest Playwright tests into CI run, some cleanups

- README.md
- abacus-integration-test/README.md
> Readme actualization

- abacus-integration-test/e2e/api.spec.ts
> Extend API test with Entitlement Store and KAS App endpoints

- abacus-integration-test/e2e/api.spec.ts
> Improve assertions and cover PLAT-2439 bug case for Entity Resolution tests

- abacus-integration-test/e2e/api.spec.ts
> Token generation improvement + Get Authorities case for Playwright API test

- abacus-and-api-integration-tests/e2e/abacus-attributes-page.spec.ts
- abacus-and-api-integration-tests/e2e/helpers/selectors.ts
> Fix Edit Value test after correspondent changes

- abacus-and-api-integration-tests/e2e/abacus-attributes-page.spec.ts
- abacus-and-api-integration-tests/e2e/helpers/selectors.ts
> Playwright tests for Add New/Remove Unnecessary order value and setting Group By value

- .github/workflows/abacus-and-api-playwright-tests.yml
- abacus-and-api-integration-tests/e2e/abacus-attributes-page.spec.ts
- abacus-and-api-integration-tests/e2e/abacus-authorities-page.spec.ts
- abacus-and-api-integration-tests/e2e/abacus-entitlements-page.spec.ts
- abacus-and-api-integration-tests/e2e/backend-api.spec.ts
- abacus-and-api-integration-tests/e2e/helpers/operations.ts
> Add negative tests for backend services (Attributes, Authorities, Entitlements)

- .github/workflows/abacus-and-api-playwright-tests.yml
- abacus-and-api-integration-tests/e2e/abacus-app.spec.ts
- abacus-and-api-integration-tests/e2e/abacus-attributes-page.spec.ts
- abacus-and-api-integration-tests/e2e/abacus-authorities-page.spec.ts
- abacus-and-api-integration-tests/e2e/abacus-entitlements-page.spec.ts
- abacus-and-api-integration-tests/e2e/backend-api.spec.ts
- abacus-and-api-integration-tests/playwright.config.ts
> TestRail-related setup, report generation and tests updates

- .github/workflows/xtest.yml
perhaps we should do all of the libs?
> chore(xtest): replace protocol/go in checkout

- xtest/test_abac.py
add java decrypt to test_abac.py
> Add test for multikas decrypt java

- .github/workflows/xtest.yml
- xtest/sdk/java/cli.sh
- xtest/test_abac.py
adds tests for https://github.com/opentdf/java-sdk/issues/103
> Add java multikas encrypt tests

- .github/workflows/check.yml
- .github/workflows/xtest.yml
- xtest/conftest.py
- xtest/requirements.txt
- xtest/sdk/py/test_unbound_policy.py
- pin pydantic to avoid [flakes](https://github.com/opentdf/platform/actions/runs/10496358169/job/29076813992?pr=1417) where pydantic 1.x is being installed
- While I'm here, run `black` (code formatter) and add `black --check` and `ruff check` (linter) to merge checks
> chore(ci): Add linting for python; pin pydantic

- xtest/nano.py
- xtest/test_nano.py
doesn't validate or verify them, though
> chore(xtest): parse nano ecdsa bindings

- abacus-and-api-integration-tests/playwright.config.ts
- xtest/conftest.py
- xtest/nano.py
- xtest/sdk/js/app-react/Dockerfile
- xtest/sdk/py/cli.py
- xtest/test_tdfs.py
This PR follows #218 by addressing Sonar alerts.  These are minor style and lint alerts, but seem easy to address.
> Code style fixes to address Sonar Alerts

- .github/workflows/xtest.yml
- xtest/README.md
- xtest/sdk/Makefile
Adds a makefile that allows you to easily build and setup the sdk clis. This should speed up the local development process.
> feat: Makefile for building sdk clis (easier local development)

- xtest/tdfs.py
- xtest/test_tdfs.py
Adds negative tests for altered policy binding, assertion modification, payload modification, and encrypted segment size modification
> feat(): Additional negative tests for policy, integrity info, assertion, and payload modification

- xtest/tdfs.py
- xtest/test_tdfs.py
> fix(): Revert "feat(): Additional negative tests for policy, integrity info, assertion, and payload modification"

- .github/workflows/xtest.yml
- xtest/conftest.py
- xtest/sdk/js/cli/cli.sh
- xtest/tdfs.py
- xtest/test_tdfs.py
> chore(xtest): Enable ec-wrapped testing of web-sdk

- xtest/conftest.py
- xtest/test_abac.py
- xtest/test_legacy.py
- xtest/test_tdfs.py
I forgot I switched from a bool to a set halfway through refactoring, apparently
> chore(ci): Fix bug in focus-sdk

- xtest/sdk/scripts/resolve-version.py
Platform and other go clients use these.
Try to figure out the requesting PR if possible
> chore(xtest): Support sha refs

- .github/workflows/xtest.yml
- Instead, check latest v. head nightly, and latest v. head v. lts weekly
> chore(xtest): Remove latest default skew tests

- xtest/sdk/go/cli.sh
- xtest/sdk/scripts/resolve-version.py
- xtest/tdfs.py
- xtest/test_abac.py
- xtest/test_tdfs.py
bump lts platform version to 0.4.34
skip tests if client uses connect rpc and platform is pre connect rpc
> feat(xtest): Skip tests if client supports connect rpc but platform does not

- .github/workflows/xtest.yml
e.g. if a pr has already merged and we want to re-run
> chore(xtest): Fix failures if tag is not found

- xtest/sdk/go/cli.sh
- xtest/sdk/java/cli.sh
- xtest/sdk/js/cli.sh
- xtest/tdfs.py
- xtest/test_policytypes.py
Currently always skipped since not implemented
> chore(xtest): Add nano plaintext policy coverage

- xtest/test_policytypes.py
- Used wrong policy type for parser
> chore(xtest): Fix type error when parsing ntdf

- .github/workflows/check.yml
- .github/workflows/xtest.yml
- pyproject.toml
- requirements.txt
* [Remove 'project.optional-dependencies' table](https://github.com/opentdf/tests/commit/638eeed57b51f8693422bd67e7852243225fcadf)
* [Use 'uv run' for tooling](https://github.com/opentdf/tests/commit/51db1884174a285534c1dba59f26dbd0a0b241c3)
> feat: tweal `project.optional-dependencies`
